### ISSUE TITLE
Implement register new together account.

### ISSUE THREAD

**Issue by learnforward2023** [learnforward2023/together-project-server#1]
## User Story (Why) 📑

Tạo một tài khoản mới

## What should I do? 🤔

- Xác định các trường cần thiết để tạo tài khoản mới.
- Tìm hiểu về session, cookie, sự khác biệt giữa chúng.
- Tim hiểu về `hashing`, `encoding`, `encrypting`, sự khác biệt.
- Tìm hiểu cách sử dụng đăng ký tài khoản mới bằng những phương thức nào?
    - Đăng ký bằng tài khoản, mật khẩu
    - Đăng ký bằng Github

## What is the GOALs? 🤩

- Hiểu và biết cách sử dụng session, cookie
- Phân biệt được sự khác nhau giữa `hashing`, `encoding`, `encrypting`, cách phù hợp để lưu trữ thông tin người dùng ở cơ sở dữ liệu
- Có thông tin về cách đăng ký tài khoản với Github

# Tasks

- [ ] Tìm hiểu về session, cookie, sự khác biệt giữa chúng.
- [ ] Tim hiểu về `hashing`, `encoding`, `encrypting`, sự khác biệt.
- [ ] Tìm hiểu cách sử dụng đăng ký tài khoản mới bằng những phương thức nào?
- [ ] Xác định các trường cần thiết để tạo tài khoản mới.
